version: 2

jobs:
 build:
   machine: true
   steps:
     # Clean up the workspace.
     - run:
          name: Clean Workspace
          command: rm -r /home/circleci/project/    
     # Checkout the code as the first step.          
     - checkout
     # Building the application 
     - run:
          name: Build
          command: | 
            cd /home/circleci/project/cas-k8s-demo
            mvn clean install           
    # Unit testing            
     - run:
          name: Test
          command: | 
            cd /home/circleci/project/cas-k8s-demo
            mvn test   
     #Docker build                        
     - run:
          name: Docker build image
          command: |
            cd /home/circleci/project/cas-k8s-demo
            docker build . -t arunprasanth45/cas-k8s-demo:1.0
     # Docker login and push                        
     - run:
          name: Docker Login and push
          command: |
           docker login --username $DOCKER_USERNAME --password=$DOCKER_PASSWORD
           docker push arunprasanth45/cas-k8s-demo:1.0
           docker logout
     # Trigger CD - Updating CD RELEASE BRANCH
     - run:
          name: Triggering CD (Merging to CD RELEASE BRANCH)
          command: |
           cd /home/circleci/project/
           git clone https://github.com/arunprasanth45/CAS-K8S-CICD-Deployment.git -b RELEASE
           git merge origin/main
           git push
           
    
           
           
           
           
           
           
