version: 2

jobs:
 build:
   machine: true
   steps:
     # CAS ENV preparation
     - run:
          name: CAS Release ENV preparation
          command: |
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh |sudo sh -s -- -b /usr/local/bin 
            sudo curl -L https://get.helm.sh/helm-v3.5.2-linux-amd64.tar.gz | tar xz && sudo mv linux-amd64/helm /bin/helm && sudo rm -rf linux-amd64            
     # Clean up the workspace.
     - run:
          name: Clean Workspace
          command: rm -r /home/circleci/project/    
     # Checkout the code as the first step.          
     - checkout
     # Building the application 
     - run:
          name: Build
          command: | 
            cd /home/circleci/project/cas-k8s-demo
            mvn clean install           
    # Unit testing            
     - run:
          name: Unit Test
          command: | 
            cd /home/circleci/project/cas-k8s-demo
            mvn test   
     #Docker build                        
     - run:
          name: Docker- building image
          command: |
            cd /home/circleci/project/cas-k8s-demo
            TAG=1.0.$CIRCLE_BUILD_NUM
            docker build . -t arunprasanth45/cas-k8s-demo:$TAG
      #Docker scanning                        
     - run:
          name: Docker- scanning image (Using trivy)
          command: |
             TAG=1.0.$CIRCLE_BUILD_NUM
             trivy --exit-code 0 --no-progress arunprasanth45/cas-k8s-demo:$TAG           
     # Docker login and push                        
     - run:
          name: Docker- pushing image into docker repo
          command: |
           TAG=1.0.$CIRCLE_BUILD_NUM
         #  echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
         #  docker push arunprasanth45/cas-k8s-demo:$TAG
         #  docker logout
     # Preparing Release
     - run:
          name: Preparing CD release helm manifest
          command: |
           TAG=1.0.$CIRCLE_BUILD_NUM
           cd /home/circleci/project/
           git clone https://$GITHUB_PERSONAL_TOKEN@github.com/arunprasanth45/CAS-K8S-CD.git -b RELEASE
           cd ./CAS-K8S-CD
           git config user.email "arunprasanth45@gmail.com"
           git config user.name "arunprasanth45"
           git config credential.helper 'cache --timeout=120'
           git merge origin/main
           cd ./helm/cas-k8s-demo
           sed -i 's/\(1.0\)\(.*)/\1:'$TAG'/' values.yaml 
           # s/\(circleci-webappdemo\)\(.*\)/\1:'$TAG'/    
     # Validating Release
     - run:
          name: Validating CD release helm manifest
          command: | 
           cd /home/circleci/project/CAS-K8S-CD/helm/cas-k8s-demo
           helm lint         
     # Publishing Release 
     - run:
          name: Publishing CD release helm manifest
          command: |         
           cd /home/circleci/project/CAS-K8S-CD
           git config user.email "arunprasanth45@gmail.com"
           git config user.name "arunprasanth45"
           git config credential.helper 'cache --timeout=120'
           git add .
           git commit -m  "Updated via CircleCI"
           git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/arunprasanth45/CAS-K8S-CD.git RELEASE

           
    
           
           
           
           
           
           
